import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import ChangePath from "@/components/ChangePath";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 080808 */}
      <body className={`} bg-[#080808]`}>
        {/* <body className={`${inter.className} bg-[#080808]`}> */}
        <ChangePath />

        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
